Bug 1954003 - Fix new implicit-int-conversion warnings from clang 21.  a=diannaS
/builds/worker/workspace/obj-build/dist/include/js/Conversions.h:364:70: error: implicit conversion loses integer precision: 'int' to 'unsigned char' [-Werror,-Wimplicit-int-conversion]
  364 |   return (bits & mozilla::FloatingPoint<double>::kSignBit) ? ~result + 1
      |   ~~~~~~                                                     ~~~~~~~~^~~
/builds/worker/workspace/obj-build/dist/include/js/Conversions.h:544:42: note: in instantiation of function template specialization 'JS::ToUnsignedInteger<unsigned char>' requested here
  544 | inline int8_t ToUint8(double d) { return ToUnsignedInteger<uint8_t>(d); }
      |                                          ^
/builds/worker/workspace/obj-build/dist/include/js/Conversions.h:364:70: error: implicit conversion loses integer precision: 'int' to 'unsigned short' [-Werror,-Wimplicit-int-conversion]
  364 |   return (bits & mozilla::FloatingPoint<double>::kSignBit) ? ~result + 1
      |   ~~~~~~                                                     ~~~~~~~~^~~
/builds/worker/workspace/obj-build/dist/include/js/Conversions.h:549:45: note: in instantiation of function template specialization 'JS::ToUnsignedInteger<unsigned short>' requested here
  549 | inline uint16_t ToUint16(double d) { return ToUnsignedInteger<uint16_t>(d); }
      |                                             ^

(cherry picked from commit 02f94f3cdc97fc3b2bc4654658230c2d896417ae)

Original Revision: https://phabricator.services.mozilla.com/D241584

Differential Revision: https://phabricator.services.mozilla.com/D330884